#!/bin/sh
if [[ $USER != root ]]; then
  echo "need root or sudo."
  exit 0
fi

[[ $(which sudo 2>/dev/null) ]] || alias sudo=''

# copy the script file to /usr/local/bin at the first time
if [[ ! $(which adhosts) ]]; then
  echo -e "\e[1m Install adhosts , and update hosts.安装adhosts并更新hosts。\e[0m"
  sudo install -c $0 /usr/local/bin/adhosts
fi

# hosts src
url_list=(
  "https://raw.githubusercontent.com/googlehosts/hosts/master/hosts-files/hosts"
  "https://adaway.org/hosts.txt"
  "https://raw.githubusercontent.com/vokins/yhosts/master/hosts"
  "https://cdn.jsdelivr.net/gh/neoFelhz/neohosts@gh-pages/full/hosts"
)

# downloading hosts
hosts_file=$(mktemp)
for url in ${url_list[*]}; do
  echo "-----"
  echo "Download hosts from " $url "..."
  curl -s $url >>$hosts_file
done

# modify some content
adhosts_start_tag='#adhosts_start_tag...All-lines-above-are-original-info.'
adhosts_end_tag='#adhosts_end_tag...'

sudo sed -i -e "1 i $adhosts_start_tag" \
  -e "$ a $adhosts_end_tag" \
  -e "/localhost/d" \
  -e "/ip6-localhost/d" \
  $hosts_file

# delete old adhosts info
sudo sed -i "/$adhosts_start_tag/,/$adhosts_end_tag/ d" /etc/hosts

# # copy /tmp/hosts to /etc/hosts
[[ -s $hosts_file ]] && sudo cat $hosts_file >>/etc/hosts

echo -e "OK!Some ads will be blocked!更新成功！你可以科学上网。可能需要使用https访问，例如\e[1;35m https://www.google.com/ \e[0m访问Google。"
echo -e "Next time , execute this command \e[1madhosts\e[0m for updating.下次执行adhosts这条命令进行更新。"
