#!/bin/sh
# copy the adhost to /usr/bin at the first time
echo "Move adhosts to /usr/bin"
sudo -S cp ./adhosts /usr/bin/
sudo -S sed -i '/adhost/d' /usr/bin/adhosts

# hosts src
url_list=(
  "https://raw.githubusercontent.com/racaljk/hosts/master/hosts"
  "https://adaway.org/hosts.txt"
  "https://raw.githubusercontent.com/vokins/yhosts/master/hosts"
  "https://raw.githubusercontent.com/sy618/hosts/master/p"
  "https://raw.githubusercontent.com/sy618/hosts/master/y"
  "https://raw.githubusercontent.com/neoFelhz/neohosts/master/nadhost"
)

# downloading hosts
for((i=0;i<${#url_list[*]};++i))
do
  url="${url_list[i]}"
  echo "Download hosts from " $url
  curl -#C - -o /tmp/"$i" "$url"
done

echo -e "\e[1;31m Updating hosts need permission to write /etc/hosts. 更新hosts需要有向/etc/hosts写入的权限 \e[0m"
# remove same content
sudo -S sed -i '/localhost/d' /tmp/1 /tmp/2 /tmp/5
sudo -S sed -i '/ip6-localhost/d' /tmp/2

# merge hosts
sudo -S cat /tmp/0 /tmp/1 /tmp/2 /tmp/3 /tmp/4 /tmp/5 >> /tmp/hosts

# copy /tmp/hosts to /etc/hosts
sudo -S cp /tmp/0 /etc/hosts

echo -e "OK!Some ads will be blocked!更新成功！你可以科学上网可。可能需要从\e[1;35m https://www.google.com/ncr \e[0m访问Google。"
